esphome:
  name: sonoffth16
  platform: ESP8266
  board: esp8285

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  # ap:
  #   ssid: "Sonoffth16 Fallback Hotspot"
  #   password: !secret ap_password

#captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret ap_key

ota:
  password: !secret device_password

status_led:
  pin: 
    number: GPIO13
    inverted: True

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "sonoffth button"
    internal: True
    on_press:
      then:
        - switch.toggle: relay    
  - platform: status
    name: "sonoffth status"

switch:
  - platform: gpio
    id: relay
    name: "sonoffth switch"
    pin: GPIO12

