substitutions:
  dev_name: sonoff_s20_2
esphome:
  name: ${dev_name}
  platform: ESP8266
  board: esp8285

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable fallback hotspot (captive portal) in case wifi connection fails
#   ap:
#     ssid: "Sonoffth16 Fallback Hotspot"
#     password: "F2yIDSuOl7TW"

# captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret device_password

ota:
  password: !secret device_password

status_led:
  pin: 
    number: GPIO13
    inverted: True

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "${dev_name} button"
    internal: True
    on_press:
      then:
        - switch.toggle: relay    
  - platform: status
    name: "${dev_name} status"

switch:
  - platform: gpio
    id: relay
    name: "${dev_name} switch"
    pin: GPIO12

sensor:
  - platform: wifi_signal
    name: "${dev_name}_wifi_signal"
    update_interval: 30s
  - platform: uptime
    name: "${dev_name}_uptime"
    update_interval: 120s
